In [1]:
import pandas as pd
import numpy as np
import tensorflow as tf
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix, accuracy_score
from sklearn.preprocessing import StandardScaler

In [2]:
df=pd.read_csv('filtered_genes_with_data_new.csv')
df

GeneSymbol    CCDC69      FGD6      SOX4     LAMC2   TACSTD2    TRIM29   
0    GSM2349019  6.738252  4.549170  6.108567  4.156697  4.656119  3.989206  \
1    GSM2349020  7.072958  4.528958  6.265788  5.010608  4.405681  3.866509   
2    GSM2349021  6.798932  3.813047  5.894221  4.478374  4.968648  3.397109   
3    GSM2349022  7.092804  3.436678  5.944107  4.756638  5.019057  3.393114   
4    GSM2349023  6.984945  3.119414  5.918883  4.151469  5.122443  4.056527   
..          ...       ...       ...       ...       ...       ...       ...   
125  GSM3184681  7.353678  3.231078  7.606823  3.444613  3.334269  3.243966   
126  GSM3184682  7.151484  2.906413  6.951401  3.771437  3.323634  3.463823   
127  GSM3184683  7.191631  3.021459  9.281144  4.436833  2.915904  3.169569   
128  GSM3184684  7.095950  3.435839  7.900018  3.339294  3.114370  3.266415   
129  GSM3184685  7.248451  3.120689  6.428618  4.006563  4.022524  3.662086   

         SOX9      TPBG       MET  ...      KRT7       FN1     SULF1   
0    5.365798  4.707697  4.635441  ...  4.186125  5.263535  6.375515  \
1    4.893197  5.614811  4.500780  ...  4.479858  5.125493  6.254908   
2    4.814469  5.075702  4.275187  ...  3.956915  4.790492  5.513411   
3    4.412138  5.470248  4.652949  ...  4.927931  4.113981  5.438981   
4    3.824814  4.581189  4.609800  ...  5.514139  5.886313  5.065742   
..        ...       ...       ...  ...       ...       ...       ...   
125  4.174610  4.708932  3.725538  ...  3.857767  7.656042  6.115056   
126  4.558928  4.944762  3.811108  ...  3.546503  6.509696  6.244244   
127  5.124605  6.971234  4.101845  ...  7.535712  6.056726  5.645666   
128  4.180494  7.561943  4.598772  ...  3.813350  7.581335  8.973389   
129  4.511479  4.372448  4.319648  ...  4.975785  5.680276  5.861450   

       GPRC5A  TNFRSF21    COL8A1     BACE2     S100A6     FRMD5  Results  
0    4.276490  5.190165  4.822482  6.015568   8.758027  4.399736        0  
1    4.363370  4.807014  4.452679  5.918429   8.745884  3.596420        0  
2    4.896741  5.122722  3.827544  5.754045   6.877546  3.899206        0  
3    4.540623  5.012037  5.058208  6.363120   7.028343  4.212995        0  
4    4.759610  5.447244  3.450222  5.216215   7.092283  4.313617        0  
..        ...       ...       ...       ...        ...       ...      ...  
125  3.299555  6.948862  3.744562  6.159438  11.639343  3.079556        0  
126  3.623063  6.091982  3.490822  6.263418  11.663062  3.139491        1  
127  5.218370  6.817701  3.942672  6.577967  11.484455  3.082578        1  
128  5.629383  7.907935  4.505491  6.574876  11.292092  3.031311        1  
129  3.636319  6.040122  3.993290  5.563441  11.505634  3.967509        1  

[130 rows x 26 columns]

In [3]:
X=df.iloc[:,1:-1].values
y=df.iloc[:,-1].values
print(X)
print(y)

[[ 6.73825159  4.54916992  6.10856712 ...  6.01556773  8.75802668
   4.39973565]
 [ 7.07295816  4.5289585   6.26578758 ...  5.91842909  8.74588388
   3.59641983]
 [ 6.79893188  3.81304677  5.89422066 ...  5.75404506  6.87754587
   3.89920621]
 ...
 [ 7.19163112  3.02145879  9.28114356 ...  6.57796698 11.48445489
   3.08257771]
 [ 7.09594959  3.43583872  7.90001766 ...  6.57487585 11.29209218
   3.03131064]
 [ 7.2484507   3.12068946  6.42861808 ...  5.56344123 11.50563434
   3.96750884]]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 0 1 1 1 1 0 1 1 1 1]


In [4]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=0)
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train=sc.fit_transform(X_train)
X_test=sc.transform(X_test)

In [5]:
ann=tf.keras.models.Sequential()
ann.add(tf.keras.layers.Dense(units=6,activation='relu'))
ann.add(tf.keras.layers.Dense(units=6,activation='relu'))
ann.add(tf.keras.layers.Dense(units=1,activation='sigmoid'))
ann.compile(
    optimizer='adam',
    loss='binary_crossentropy', #categorical_crossentropy #for-reg mean_squared_error
    metrics=['accuracy'] #for-reg no metrics
)
ann.fit(X_train,y_train,batch_size=32,epochs=100)
y_pred=ann.predict(X_test)
from sklearn.metrics import confusion_matrix, accuracy_score
cm=confusion_matrix(y_test,y_pred>0.5)
print(cm)
accuracy_score(y_test,y_pred>0.5)

Epoch 1/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.4446 - loss: 0.7033
Epoch 2/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.4046 - loss: 0.7027 
Epoch 3/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.4421 - loss: 0.6972 
Epoch 4/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.4203 - loss: 0.6979 
Epoch 5/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.4283 - loss: 0.6992 
Epoch 6/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.4530 - loss: 0.6987 
Epoch 7/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.4933 - loss: 0.6951 
Epoch 8/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5232 - loss: 0.6906 
Epoch 9/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.4868 - loss: 0.6933 
Epoch 10/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.4965 - loss: 0.6908 
Epoch 11/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.4628 - loss: 0.6945 
Epoch 12/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.4966 - loss

0.5384615384615384

In [6]:
from xgboost import XGBClassifier
classifier=XGBClassifier()
classifier.fit(X_train,y_train)
y_pred=classifier.predict(X_test)
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.6538461538461539

In [16]:
from catboost import CatBoostClassifier
classifier=CatBoostClassifier()
classifier.fit(X_train,y_train)
y_pred=classifier.predict(X_test)
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

Learning rate set to 0.003919
0:	learn: 0.6913446	total: 66.6ms	remaining: 1m 6s
1:	learn: 0.6906666	total: 68.4ms	remaining: 34.1s
2:	learn: 0.6892743	total: 70ms	remaining: 23.3s
3:	learn: 0.6882618	total: 72ms	remaining: 17.9s
4:	learn: 0.6868004	total: 73.5ms	remaining: 14.6s
5:	learn: 0.6860853	total: 75.3ms	remaining: 12.5s
6:	learn: 0.6847100	total: 76.8ms	remaining: 10.9s
7:	learn: 0.6835333	total: 78.5ms	remaining: 9.73s
8:	learn: 0.6823111	total: 80.1ms	remaining: 8.81s
9:	learn: 0.6806261	total: 81.5ms	remaining: 8.07s
10:	learn: 0.6790954	total: 83.1ms	remaining: 7.47s
11:	learn: 0.6777602	total: 84.7ms	remaining: 6.97s
12:	learn: 0.6768378	total: 86.1ms	remaining: 6.54s
13:	learn: 0.6755615	total: 87.6ms	remaining: 6.17s
14:	learn: 0.6744075	total: 89.2ms	remaining: 5.86s
15:	learn: 0.6730863	total: 90.8ms	remaining: 5.58s
16:	learn: 0.6718729	total: 92.6ms	remaining: 5.35s
17:	learn: 0.6708034	total: 94.6ms	remaining: 5.16s
18:	learn: 0.6694251	total: 96.5ms	remaining: 4.

0.6923076923076923

In [9]:
model=LogisticRegression(random_state=42)
model.fit(X_train,y_train)
y_pred=model.predict(X_test)
print(accuracy_score(y_test,y_pred))
confusion_matrix(y_test,y_pred)

0.6153846153846154


array([[11,  5],
       [ 5,  5]], dtype=int64)

In [10]:
from sklearn.neighbors import KNeighborsClassifier
model=KNeighborsClassifier(n_neighbors=3,metric='minkowski',p=2)
model.fit(X_train,y_train)
y_pred=model.predict(X_test)
print(accuracy_score(y_test,y_pred))
confusion_matrix(y_test,y_pred)

0.6538461538461539


array([[11,  5],
       [ 4,  6]], dtype=int64)

In [11]:
from sklearn.svm import SVC
model=SVC(kernel='rbf',random_state=0)
model.fit(X_train,y_train)
y_pred=model.predict(X_test)
print(accuracy_score(y_test,y_pred))
confusion_matrix(y_test,y_pred)

0.5769230769230769


array([[9, 7],
       [4, 6]], dtype=int64)

In [12]:
from sklearn.naive_bayes import GaussianNB
model=GaussianNB()
model.fit(X_train,y_train)
y_pred=model.predict(X_test)
print(accuracy_score(y_test,y_pred))
confusion_matrix(y_test,y_pred)

0.5


array([[9, 7],
       [6, 4]], dtype=int64)

In [13]:
from sklearn.tree import DecisionTreeClassifier
model=DecisionTreeClassifier(criterion='gini',random_state=0)
model.fit(X_train,y_train)
y_pred=model.predict(X_test)
print(accuracy_score(y_test,y_pred))
confusion_matrix(y_test,y_pred)

0.6153846153846154


array([[12,  4],
       [ 6,  4]], dtype=int64)

In [14]:
from sklearn.ensemble import RandomForestClassifier
model=RandomForestClassifier(n_estimators=400,criterion='entropy',random_state=0)
model.fit(X_train,y_train)
y_pred=model.predict(X_test)
print(accuracy_score(y_test,y_pred))
confusion_matrix(y_test,y_pred)

0.7307692307692307


array([[11,  5],
       [ 2,  8]], dtype=int64)

In [15]:
from sklearn.ensemble import GradientBoostingClassifier
model=GradientBoostingClassifier()
model.fit(X_train,y_train)
y_pred=model.predict(X_test)
print(accuracy_score(y_test,y_pred))
confusion_matrix(y_test,y_pred)

0.6538461538461539


array([[9, 7],
       [2, 8]], dtype=int64)

   ---------------------------------------- 0.0/101.7 MB ? eta -:--:--
   ---------------------------------------- 0.0/101.7 MB ? eta -:--:--
   ---------------------------------------- 0.0/101.7 MB ? eta -:--:--
   ---------------------------------------- 0.0/101.7 MB ? eta -:--:--
   ---------------------------------------- 0.0/101.7 MB ? eta -:--:--
   ---------------------------------------- 0.1/101.7 MB 3.2 MB/s eta 0:00:32
   ---------------------------------------- 0.1/101.7 MB 3.2 MB/s eta 0:00:32
   ---------------------------------------- 0.1/101.7 MB 3.2 MB/s eta 0:00:32
   ---------------------------------------- 0.1/101.7 MB 657.6 kB/s eta 0:02:35
   ---------------------------------------- 0.1/101.7 MB 654.9 kB/s eta 0:02:36
   ---------------------------------------- 0.2/101.7 MB 756.6 kB/s eta 0:02:15
   ---------------------------------------- 0.2/101.7 MB 756.6 kB/s eta 0:02:15
   ---------------------------------------- 0.2/101.7 MB 756.6 kB/s eta 0:02:15
   --------

ERROR: Could not install packages due to an OSError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\bhave\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\catboost\\_catboost.pyd'
Consider using the `--user` option or check the permissions.


[notice] A new release of pip is available: 24.0 -> 24.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip
